/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estructura;



import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Carlos
 */
public class Index extends javax.swing.JFrame {
int mouseX;
int mouseY;
    
    public Index() {
        initComponents();
        this.setLocationRelativeTo(null);

        //ImageIcon BotonBanco = new ImageIcon("src/img/banco.png");
        //OpcF03.setIcon(new ImageIcon(BotonBanco.getImage().getScaledInstance(30, 35, Image.SCALE_SMOOTH)));
        
        ImageIcon BotonMcd = new ImageIcon("src/img/mcd.png");
        OpcF06.setIcon(new ImageIcon(BotonMcd.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));
        
        ImageIcon BotonRaton = new ImageIcon("src/img/raton2.png");
        OpcF07.setIcon(new ImageIcon(BotonRaton.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));
        
        ImageIcon BotonBanco = new ImageIcon("src/img/banco.png");
        OpcF03.setIcon(new ImageIcon(BotonBanco.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH)));
        
        ImageIcon heart = new ImageIcon("src/img/heart.png");
        heartIcon.setIcon(new ImageIcon(heart.getImage().getScaledInstance(10, 10, Image.SCALE_SMOOTH)));
        
        ImageIcon BotonCerrar = new ImageIcon("src/img/cerrar.png");
        cerrar.setIcon(new ImageIcon(BotonCerrar.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        ImageIcon BotonMinimizar = new ImageIcon("src/img/minimizar.png");
        minimizar.setIcon(new ImageIcon(BotonMinimizar.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Footer = new javax.swing.JPanel();
        heartIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        cerrar = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        BarMenu = new javax.swing.JPanel();
        OpcF06 = new javax.swing.JButton();
        OpcF07 = new javax.swing.JButton();
        OpcF03 = new javax.swing.JButton();
        PanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Footer.setBackground(new java.awt.Color(34, 42, 58));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("por Carlos Castillo");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hecho con");

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(heartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(43, 43, 43))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heartIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FooterLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FooterLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 310, 20));

        Header.setBackground(new java.awt.Color(52, 55, 63));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        minimizar.setContentAreaFilled(false);
        minimizar.setDefaultCapable(false);
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(minimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 30));

        BarMenu.setBackground(new java.awt.Color(52, 55, 63));
        BarMenu.setPreferredSize(new java.awt.Dimension(216, 413));

        OpcF06.setToolTipText("");
        OpcF06.setBorderPainted(false);
        OpcF06.setContentAreaFilled(false);
        OpcF06.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mcd-selec.png"))); // NOI18N
        OpcF06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcF06ActionPerformed(evt);
            }
        });

        OpcF07.setToolTipText("");
        OpcF07.setBorderPainted(false);
        OpcF07.setContentAreaFilled(false);
        OpcF07.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/raton2-select.png"))); // NOI18N
        OpcF07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcF07ActionPerformed(evt);
            }
        });

        OpcF03.setToolTipText("");
        OpcF03.setBorderPainted(false);
        OpcF03.setContentAreaFilled(false);
        OpcF03.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banco-select.png"))); // NOI18N
        OpcF03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcF03ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarMenuLayout = new javax.swing.GroupLayout(BarMenu);
        BarMenu.setLayout(BarMenuLayout);
        BarMenuLayout.setHorizontalGroup(
            BarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OpcF06, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpcF07, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpcF03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BarMenuLayout.setVerticalGroup(
            BarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarMenuLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(OpcF03, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(OpcF06, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(OpcF07, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        getContentPane().add(BarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 50, 350));

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 310, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int coordX = evt.getXOnScreen();
        int coordY = evt.getYOnScreen();
        
        this.setLocation(coordX-mouseX, coordY-mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
                
    }//GEN-LAST:event_HeaderMousePressed

    private void OpcF06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcF06ActionPerformed
        int alto = PanelPrincipal.getHeight();
        int ancho = PanelPrincipal.getWidth();
        
        E06 PanelMcd = new E06();
        PanelMcd.setSize(ancho,alto);
        PanelMcd.setLocation(1,1);
        
        PanelPrincipal.removeAll();
        PanelPrincipal.add(PanelMcd, BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_OpcF06ActionPerformed

    private void OpcF07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcF07ActionPerformed
        int alto = PanelPrincipal.getHeight();
        int ancho = PanelPrincipal.getWidth();
        
        E07 PanelRaton = new E07();
        PanelRaton.setSize(ancho,alto);
        PanelRaton.setLocation(1,1);
        
        PanelPrincipal.removeAll();
        PanelPrincipal.add(PanelRaton, BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_OpcF07ActionPerformed

    private void OpcF03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcF03ActionPerformed
        int alto = PanelPrincipal.getHeight();
        int ancho = PanelPrincipal.getWidth();
        
        E03 PanelBanco = new E03();
        PanelBanco.setSize(ancho,alto);
        PanelBanco.setLocation(1,1);
        
        PanelPrincipal.removeAll();
        PanelPrincipal.add(PanelBanco, BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_OpcF03ActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        this.setExtendedState(1);
    }//GEN-LAST:event_minimizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarMenu;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JButton OpcF03;
    private javax.swing.JButton OpcF06;
    private javax.swing.JButton OpcF07;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel heartIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton minimizar;
    // End of variables declaration//GEN-END:variables

    private ImageIcon ImageIcon(String srcimgmenupng) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
